# Generated by Django 4.0.1 on 2022-01-31 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OktaGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a name', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Describe the group', null=True)),
                ('profile', models.JSONField()),
                ('okta_id', models.CharField(blank=True, max_length=100, null=True)),
                ('source_system', models.CharField(blank=True, max_length=255, null=True)),
                ('source_type', models.CharField(blank=True, max_length=255, null=True)),
                ('member_count', models.IntegerField(default=0)),
                ('allow_join', models.BooleanField(default=False)),
                ('allow_leave', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'permissions': (),
            },
        ),
    ]
