# Generated by Django 4.0.1 on 2022-02-04 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oktagroup',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
