# Generated by Django 4.0.2 on 2022-03-05 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okta', '0002_oktagroup_hidden'),
    ]

    operations = [
        migrations.CreateModel(
            name='OktaUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('okta_id', models.CharField(blank=True, max_length=100, null=True)),
                ('firstName', models.CharField(blank=True, max_length=255, null=True)),
                ('lastName', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('login', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('secondEmail', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, help_text='Describe the group', null=True)),
                ('profile', models.JSONField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['email'],
                'permissions': (),
            },
        ),
    ]
