# Generated by Django 4.0.2 on 2022-08-08 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('okta', '0003_oktauser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oktagroup',
            options={'ordering': ['name'], 'permissions': (('list_groups', 'Can List Groups'),)},
        ),
        migrations.AlterModelOptions(
            name='oktauser',
            options={'ordering': ['email'], 'permissions': (('list_users', 'Can List Users'),)},
        ),
        migrations.RemoveField(
            model_name='oktauser',
            name='description',
        ),
    ]
